name: The Common Ground Sophisticate
favicon: null
layout_spectrum: 0.75546
typography_spectrum: 0.76033
title: The Common Ground Sophisticate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01010d'
    - '#928575'
    - '#fb4193'
    - '#c5bfb4'
  brandStrength: 0.6875
  lightness: 0.25
  saturation: 0.062094346387311816
  rhythmicContrast: 0.6412758557125926
purpose: []
